apiVersion: v1
kind: Service
metadata:
  name: bbcrud-svc
  labels: # Use same labels as pod. This is not required but is just a good practice.
    environment: dev
    app: bbcrud
    version: v1
spec:
  selector:
    app: bbcrud
  ports:
  - port: 8080 # The pod's container port
  type: NodePort # Allocates a port on each node for the service
