apiVersion: v1
kind: Pod
metadata:
  name: bbcrud
  labels:
    environment: dev
    app: bbcrud
    version: v1
spec:
  containers:
    - name: bbcrud
      image: "bbmicroservicesacr.azurecr.io/bbmicroservicescrud:1"
      resources:
          requests:
            memory: "128Mi" # 128Mi = 128 mebibytes
            cpu: "500m"     # 500m = 500 milliCPUs
          limits:
            memory: "128Mi"
            cpu: "500m"
      ports:
        - containerPort: 8080
